### ISSUE TITLE
[bug] the mod makes captain unable to deploy his beacons

### ISSUE THREAD

**Issue by Littleevo** [CxVercility/CommandoRebalance#1]
i have no idea why it's happening, but installing the mod causes captain's beacons to be already spent at the start of every stage.

**Comment by CxVercility** [comment]
Weird, I'll take a look at it tomorrow. Thanks.

Littleevo ***@***.***> schrieb am Sa., 5. März 2022, 23:48:

**Comment by Littleevo** [comment]
i'm sorry. that's a vanilla bug. it doesn't have to do anything with the mod.
