### ISSUE TITLE
[bug] config doesn't show up

### ISSUE THREAD

**Issue by Littleevo** [CxVercility/CommandoRebalance#2]
the mod description says customizable stats for commando, but it doesn't seem to make any config files.

**Comment by CxVercility** [comment]
> the mod description says customizable stats for commando, but it doesn't seem to make any config files.

It does, you're probably just looking for the wrong file. It doesn't contain the mod's name in it, just search for "vercility" in the modmanager or your file explorer. It should be com.Vercility.Ror or something like that.

I already noticed this error at some point in the past, but changing it now would break everyone's config files when they update and they probably wont notice/know why.
