### ISSUE TITLE
[suggestion] making grenades stick

### ISSUE THREAD

**Issue by Littleevo** [CxVercility/CommandoRebalance#3]
this would make the grenades much less frustrating to deal with. or maybe they just explode on impact. anything to free commando from the hellish mercy of the physics engine.

**Comment by CxVercility** [comment]
Not really within the scope of things I can do.

I have zero experience with both C# and the Risk of Rain Code.

You should ask someone on the modding discord, there is a suggestion channel. I'll be happy to merge their feature into this project if someone is willing to do it.
